annotations:
  artifacthub.io/license: Apache-2.0
apiVersion: v2
appVersion: v1.6.1
dependencies:
- condition: dex.enabled, global.dex.enabled
  name: dex
  repository: https://charts.dexidp.io
  tags:
  - dex
  version: 0.12.1
- condition: minio.enabled, global.minio.enabled
  name: minio
  repository: https://charts.min.io/
  tags:
  - minio
  version: 5.0.10
- condition: kubed.enabled, global.kubed.enabled
  name: kubed
  repository: https://charts.appscode.com/stable/
  tags:
  - kubed
  version: 0.13.2
- condition: epinio-ui.enabled
  name: epinio-ui
  repository: https://epinio.github.io/helm-charts
  tags:
  - epinio-ui
  version: 1.5.3
description: Epinio deploys Kubernetes applications directly from source code in one
  step.
home: https://github.com/epinio/epinio
icon: https://raw.githubusercontent.com/epinio/helm-charts/main/assets/epinio.png
keywords:
- epinio
- paas
maintainers:
- email: team@epinio.io
  name: SUSE
name: epinio
sources:
- https://github.com/epinio/epinio
version: 1.7.0
