name: Build epiniod image

on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: chrisdickinson/setup-yq@latest     # Install yq
      - uses: WyriHaximus/github-action-helm3@v2 # Install helm
      - name: Docker image tag
        id: get-tag
        run: |
          helm repo add epinio https://epinio.github.io/helm-charts
          helm repo update
          latestRelease=$(helm show chart epinio/epinio  | yq r - version)
          echo "::set-output name=tag::$latestRelease"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: images/.
          tags: ghcr.io/epinio/epiniod:${{ steps.get-tag.outputs.tag }}, ghcr.io/epinio/epiniod:latest
          build-args: |
            VERSION=${{ steps.get-tag.outputs.tag }}
