name: Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v2.1
        with:
          version: v3.7.2

      - name: Add Helm dependency repos
        run: |
          helm repo add minio https://charts.min.io/
          helm repo add appscode https://charts.appscode.com/stable/
          helm repo add epinio https://epinio.github.io/helm-charts
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
